apiVersion: skaffold/v2beta19
kind: Config
metadata:
  name: mini-proj
build:
  artifacts:
  - image: ravi113/client
    context: posts
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - infra/k8s/client.yaml
    - infra/k8s/comments.yaml
    - infra/k8s/event-bus.yaml
    - infra/k8s/ingress-controller.yaml
    - infra/k8s/moderated.yaml
    - infra/k8s/posts-deploy.yaml
    - infra/k8s/posts-service.yaml
    - infra/k8s/query.yaml
